version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on: 
      - influxdb
    volumes:
      - grafana:/var/lib/grafana
    ports: 
      - 3000:3000
    logging:
      driver: json-file
      options: 
        max-file: "5"
        max-size: "25m"

  telegraph:
    image: arm32v7/telegraf:1.14
    container_name: telegraph
    restart: always
    depends_on: 
      - influxdb
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes: 
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
  influxdb:
    image: arm32v7/influxdb:1.8
    container_name: influxdb
    restart: always
    volumes: 
      - influxdb:/var/lib/influxdb
    logging:
      driver: json-file
      options: 
        max-file: "5"
        max-size: "25m"

volumes:
  grafana:
  influxdb: